### ISSUE TITLE
conformity indicator of network services

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/gp-data-service-linking-simplification#12]
In the consolidated proposal presented by JRC,  recommends to keep the service metadata as currently described in the Technical Guidance documents. due to  the provision of conformity indicators.

This is not in line with the recommandation of the MIG-T  "_further recommends that there should be one "source of truth" for service metadata, ideally as provided by the service itself (e.g. in its Capabilities document)."_

It is  not necessary to use standalone  service metadata or a  capabilities element, to provide this information.  It also contradicts with the description of the ApplicationProfile in the same consolidated proposal presented by JRC ;

"By using the above mentioned codelist values coming from the central INSPIRE Registry, it would imply that the described ResourceLocator URL would refer to an INSPIRE Spatial Data Service, fulfilling all the applicable Technical Guidelines requirements." 
So by using  a value of https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType, you indicate the service is conformant.

**Comment by dartasensi** [comment]
Dear @idevisser 

I see your point. I'll be honest: the use of the `applicationProfile` as **implication of conformity** was a quite convoluted tentative of simplification.
So, I think we would not use the `applicationProfile` for this scope and we should rely on the declarations in the service's metadata/GetCap. Please, see also my reply [here](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/13#issuecomment-877116752) on keeping the _Conformity declaration_ inside the `ExtendedCapabilities`.

**Comment by idevisser** [comment]
See  also the comment of @AntoRot in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/13 ,  we should avoid to extend the capabilities

**Comment by MarieLambois** [comment]
I fully agree with @AntoRot and @idevisser that the extended capabilities should be removed. It is a major point in the INSPIRE specification. I you want to have conformity in the GetCapabilities then why not a keyword:

`<Keyword vocabulary="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</Keyword>`

**Comment by idevisser** [comment]
we have remapped the metadata elements form the extended capabilities to existing elements
