### ISSUE TITLE
predefined <versus> direct download

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/gp-data-service-linking-simplification#2]
Hi,

there is an open issue in the discussion paper regarding a distinction between predefined and direct download datasets;
I think we need this distinction, especially in the context of the new ODPSI-DIR where a difference between API/services and bulk-download is made.

Erik

**Comment by dartasensi** [comment]
@oberseri if this distinction is really relevant for the data consumption, I would propose the use of a codelist value in the `description` element of the involved Resource Locator. What do you think?

**Comment by oberseri** [comment]
I am not sure, if this distinction is relevant (WFS-direct download <> WFS predefined) - the distinction WFS <> Atom is done by the ProtocolValue.

Much more relevant would be the possibilty to make a distinction between the link to the harmonised dataset an an (possibly additional) as-is version of the same dataset

**Comment by dartasensi** [comment]
Dear @oberseri 

that's exactly what I was thinking about this open issue.
I don't know what kind of benefit it would bring to formalize (eg. with explicit presence/use of some elements or codelist) the distinction between links for a Direct or Predefined dataset download.
Let me expose my knowledge of the topic (and therefore my view on it):
- the DirectDownload is done through the possibilities offered by the OGC specifications of that service. So, by crafting an exact WFS query (with a custom CRS, outputformat and so on) the WFS service will process it and provide you the response, that we call direct download dataset. Is it correct?
- instead, what we call Predefined dataset is a dataset obtained from WFS, prepared by the service provider (or the data owner). For instance, providing the original as-is shapefile, or a curated GML with a selection/combination of some parameters (bbox, etc). Is it correct?

So, once you have access to the WFS service, it will be relatively easy to retrieve and consume the dataset.
Please, help me understand the difference and the need.

Instead, about the WFS <> Atom, of course it could be done through the `protocolValue` element.

Regarding the possibility to make a distinction for the harmonised VS as-is, I've got an idea to apply to the consolidated proposal, and I will publish it soon.

**Comment by AntoRot** [comment]
The comments were taken into account in the initial discussions and proposals of this work.
The issue can be closed.
