### ISSUE TITLE
Wrong reference to the TG Requirement 1.8

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#21]
In the [latest proposal](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md), we can read in the section 8.1:

> 
> In particular, TG Requirement 1.8 of INSPIRE MD TG expresses the obligation to provide online access, if available, to the described data set or data set series.
> 
> Furthermore, it suggests that at least two locators need to be expressed in the data set metadata: one for a View Service and one for a Download Service.

The current wording of the TG Requirement 1.8 doesn't include any suggestions about providing at least a locator for a View Service and another one for a Download Service.
This was instead the new proposal of the TG Requirement 1.8 included in the Discussion Paper.

Consequently the second sentence quoted above should be removed or reworded.

**Comment by fabiovin** [comment]
Dear @AntoRot,

thank you for your comment.

The intention was to highlight that as view and download services are mandatory then at least two resource locators shall be present.
For this reason, the multiplicity of this element is intrinsically "_2..*_".
In any case, we will try to rephrase the sentence.
