### ISSUE TITLE
Distinguish between requirements and recommendations

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#22]
The requirements C and D defined in the tables in the section 8.1 for [gmd:protocol element](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#requirement-gmdprotocol-element) and [gmd:applicationProfile element](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#requirement-gmdapplicationprofile-element) use verbal forms (i.e. SHOULD and MAY) more typical of recommendations than requirements.

My proposal is to split the current requirements in two groups: Requirements (A and B) and Recommendations (C and D).

**Comment by fabiovin** [comment]
Dear @AntoRot,

you are right, looking at the first verbal forms, the requirements C and D look like recommendations, but the intention was to create requirements, especially for the gco:CharacterString encoding for which the use of the codelist label is required for the value of the element.

What do you think?

**Comment by AntoRot** [comment]
Dear @fabiovin,

if gco:CharacterString encoding is used then a specific requirement (by using the related verbal forms) can be defined instead of a recommendation, as I saw it was done by @dartasensi with the pull request https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/31.

Thanks!
