### ISSUE TITLE
Clarify what label to use for <gmd:protocol> element

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#23]
The Requirement C for the [\<gmd:protocol> element](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#requirement-gmdprotocol-element) recommends that the text value of the gmx:Anchor element should match the **_related codelist label_**.
The Requirement D requires that in case of the use of `gco:CharacterString` element the text value SHALL match the **_related codelist label_**.

As the [ProtocolValue codelist](https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue) published in the INSPIRE Registry refers to external controlled vocabularies (i.e. OGC Service Types register for all items except Atom), what above should be better specified by explaining that _**related codelist labe**l_ means to use the label defined in the source vocabulary and not the label in the INSPIRE Registry.

**Comment by MarieLambois** [comment]
Be careful that all protocols are not from OGC. There is ATOM feed already but we could have more in future. I would stock to what we have governance on so the INSPIRE registry.

**Comment by AntoRot** [comment]
Indeed I specified that the current INSPIRE register includes all items coming from OGC vocabulary except Atom. 
What I wanted to say is that, based on the examples provided, the labels to be used are those ones coming from the source vocabulary (i.e. OGC labels for csw, wms, wmts, wcs, sos, wfs and Atom label for Atom format). I revised the comment accordingly.

If we will decide to use the labels provided in the INSPIRE register, then the examples should be revised by including those labels as text values.

**Comment by fabiovin** [comment]
Dear all,

since the "ProtocolValue" codelist published in the INSPIRE Registry refers to different external vocabularies, we are proposing to use the labels in the INSPIRE Registry.
This can also facilitate the use/management of the values in the different languages, even if at the moment there are no translations available.

See related pull request https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/31
