### ISSUE TITLE
Labels expressed in the metadata language

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#24]
The Requirements C and D for [\<gmd:protocol> element](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#requirement-gmdprotocol-element) and for [\<gmd:applicationProfile> element](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#requirement-gmdapplicationprofile-element) recommend to use the codelist labels expressed in the metadata language.

As in case of `<gmd:protocol>` element the labels are acronyms in most cases (i.e. wms, csw, wfs, ...) the recommendation above doesn't make sense.

In case of `<gmd:applicationProfile>` element, the Regulation 1205/2008 in Part D3 also provides the language-neutral values for the Spatial Data Service types. Consequently the Requirements should allow for the use of either language-neutral values or the labels expressed in the metadata language.

**Comment by idevisser** [comment]
The reason why the recommendation has been made to include the labels in the metadata language is to facilitate the different spellings of the protocols (OGC:WMS, WMS, ...) that are now common in the Member States. It is therefore not  exactly the language, but of the usual spelling of the abbreviations in a Member State. OGC also leaves room for that, they only give a preference for the label to be used. The Anchor with the URI is machine readable, and this should exactly contain a common agreed value. The label is human readable, and should fulfill that role.
