### ISSUE TITLE
Add a requirement about the combination of protocol and applicationProfile

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#25]
The values to be used for the `<gmd:protocol>` element and for `<gmd:applicationProfile>` element are strongly connected, in the sense that if a certain value is used for the protocol then a well specific value shall be used for the application profile. In other words, if I use "wms" for the protocol element then I'm required to use "view" and no other value for the application profile.

I think that adding a requirement about the proper combination of protocol and application profile could be useful, even with a view to a related check in the validator.

The allowed combination should be as follows:

|Protocol|Application Profile|
| :- | :- |
|csw|discovery|
|wms|view|
|wmts|view|
|wfs|download|
|wcs|download|
|sos|download|
|atom|download|

**Comment by MarieLambois** [comment]
I fully understand your idea but I think this extra checking would be hard to maintain and thus soon create unexpected errors in the validator. For example we had recently in the MIG-T a proposal for good practice to have WMS as a download service. This would make this mapping already obsolete ;-) Also OGC APIs would be missing from the list.

**Comment by AntoRot** [comment]
I think that the definition of the requirements in the document we are discussing should be based on the normative references listed in the [section 4](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#4-normative-references-) in the version currently in force.

Furthermore, your comment leads me to think that we need a clarification about the binding value of good practices against the TGs. Reading the [procedure for proposing and endorsing the good practices](https://inspire.ec.europa.eu/portfolio/good-practice-library), I have deduced that a good practice doesn't automatically imply new requirements or recommendations but it can be the premise for the development of new or extension of existing TGs. That to say that, for example, if the good practice for the WMS as a download service will be endorsed I presume that will need to be transposed in a new or an extension of the INSPIRE Download TG. Maybe the colleagues from JRC could clarify that.
In addition, with reference to the OGC APIs, in the conformance section it is declared that currently the requirements expressed for the Download Services are not applicable for specifications based on OGC APIs (about this, I'm wondering why the OAPIF GP document is included in the normative references).

Anyway, in order to meet your considerations, a possible solution could be to publish the mapping in an ad-hoc cross-map register in the INSPIRE Registry that can be updated and extended (by following the rules defined for the extentions of the registers) by including new items. In a similar way of the Protocol Value codelist where the OGC APIs are not included currently.

**Comment by oberseri** [comment]
Actually the <gmd:protocol> element and the <gmd:applicationProfile> element are connected in an one:many relationship. We would not need the gmd.applicationProfile as long as we do not make a difference between wms:getCap (view) and wms:getMap (download) or something like that ... . But maybe it could be necessary for future service developments.

see also https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/17#issuecomment-906272647

**Comment by AntoRot** [comment]
The issue was discussed and the proposal of adding a requirement not accepted.
I'm closing this issue.
