### ISSUE TITLE
No requirements for <gmd:name> element

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#26]
In the examples provided in the [Annex A](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#annex-a-examples-) the `<gmd:name>` element is also used. 

As the use of that element is already recommended in the INSPIRE MD TG, if no specific requirement is to be defined in the Simplification Good Practice document, I would avoid its use in the examples.

**Comment by fabiovin** [comment]
Dear @AntoRot,

we reviewed your comment and since we created the snippet as an example and sometimes these examples are copied and pasted, we think it is useful to keep the "name" element.
