### ISSUE TITLE
Normative references

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/gp-data-service-linking-simplification#27]
INSPIRE MD TG - JRC is based on [ISO 19115] EN ISO 19115:2005, Geographic information – Metadata (ISO 19115:2003)
the reference to ISO 19115-2:2019 - ISO 19115-2:2019, Geographic information — Metadata — Part 2: Extensions for acquisition and processing seems not correct

**Comment by fabiovin** [comment]
Dear @idevisser,

thank you for your comment, we will revise it.
