### ISSUE TITLE
Requirement: <srv:operatesOn> element and Requirement: <wms:MetadataURL> and <wfs:MetadataURL> elements

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/gp-data-service-linking-simplification#28]
In the requirement for scenario 2  is specified that the metadata is  available in a Discovery Service catalog. I think this is also the case in the requirement for scenario1. Please articulate the requirements in the same way, whether to include both or not

**Comment by fabiovin** [comment]
Dear @idevisser,

thank you for your comment, we will do it.
