### ISSUE TITLE
"virtual datasets"

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/gp-data-service-linking-simplification#3]
The "virtual datasets" mentioned in the discussion paper could be aggregated to _dataset series_ with ONE md-set.

Erik

**Comment by dartasensi** [comment]
Dear @oberseri 

I would agree with you on this point. The mentioned _"virtual dataset"_ can be seen as dataset series, if this aggregation can be describe through its lineage.

**Comment by dartasensi** [comment]
By looking at the elapsed time since your initial contribution, I would also close this issue, if no other opinions will be soon provided by the subgroup.
