### ISSUE TITLE
simplification of service md

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/gp-data-service-linking-simplification#4]
We should leave all standard md-fields within the  service-getCap response mandatory und not suggest to remove them - why?
More info about the service is better than less ... - the main thing is, that's standard response and that's mandatory.

Erik

**Comment by idevisser** [comment]
I guess you overlooked this note; "The simplification proposed in the table only refers to the INSPIRE requirements. Where the base standard (e.g. WMS, WFS) requires additional metadata elements, these have to be provided as well (to be compliant with the base standard)."

So remove means remove the requirements from te INSPIRE documentation. 
Beside that, You can still provide  all possible metadata in the capabilities, it's only not required by INSPIRE anymore

**Comment by dartasensi** [comment]
About this point, I fully agree with @idevisser, and I would also close this issue, if no other opinions will be provided by the subgroup.
