### ISSUE TITLE
Duplicate requirements / reorganisation requirements classes

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#45]
Requirement /req/coupled-resource-operateson-locator duplicates (although not exactly, see #38) requirement metadata/2.0/req/sds/coupled-resource from the TG metadata.

Requirement /req/coupled-resource-metadataurl-locator duplicates requirements 13 and 14 of the TG View.

![billede](https://user-images.githubusercontent.com/11427611/151868641-467a6346-0196-48b4-acdb-ea3db2fbf3ff.png)

I expected to find that requirement /req/coupled-resource-metadataurl-locator would duplicate requirements in the TG Download as well, but the mapping to `wfs:MetadataURL` is only present in an informative table, not in a requirement. This is probably something that should be dealt with with an update to the TG Download specification.

![billede](https://user-images.githubusercontent.com/11427611/151868811-037204f3-8a9b-4d6e-81a6-f4dcf7b5d128.png)

For Atom, a requirement regarding the implementation of the Coupled Resource is present, though:

![billede](https://user-images.githubusercontent.com/11427611/151869009-7d1435f7-d0d5-4d69-8a47-ee4840747790.png)

![billede](https://user-images.githubusercontent.com/11427611/151869120-9014df5c-1ca0-4a24-bc0e-20d7bd5b4425.png)

As written in December via mail: 

I think it is important
- to group the requirements into requirements classes according to what it is exactly they are setting a requirement for (“service metadata” is not specific enough in this case, what is it you would test using the validator, see screenshot below):
  - ISO/TS 19139:2007 dataset metadata record
  - OGC WFS service
  - OGC WMS service
  - Atom service
- not to repeat any requirements already present in other TGs, but instead
  - adding a dependency to that TG
  - or remove the requirements class if it does not actually define additional requirements

It seems that especially requirements class INSPIRE-Network-Service-Metadata-Coupled-Resource deserves a closer look.

![billede](https://user-images.githubusercontent.com/11427611/151870146-1262e329-dbc8-4b0e-8daa-42b8736d7730.png)

**Comment by AntoRot** [comment]
I realized that I had already opened an issue (albeit less detailed) about this in November 2021 :) https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/30

**Comment by jescriu** [comment]
Dear @AntoRot,
I closed issue #30, since it was duplicated (and less detailed).
Hope you agree on it.
Jordi

**Comment by jescriu** [comment]
Dear @heidivanparys, @MarieLambois, @idevisser and @AntoRot,
I updated https://github.com/jescriu/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md taking into account the outcomes of this issue.
Please, take a look.
I will proceed with a pull request (from my repository to the official Data-service linking simplification repository) when checking the missing issues (#46, #47) tomorrow.
Thank you all.

**Comment by jescriu** [comment]
I created a pull request and merged it into https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md
Please, @heidivanparys, @AntoRot, @idevisser, @MarieLambois, revise it.

**Comment by AntoRot** [comment]
Dera @jescriu,

It's ok to me!
