### ISSUE TITLE
Keyword mapping for keywords from thesauri (WFS)

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#46]
This issue is a follow-up on a part of the discussion in #39 (repeating the relevant parts here), as this is important for the mapping of keywords.

The mapping of keywords is not really described in the [TG download](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services), it only has the table below, and gives an example for `inspire_common:Keyword`, not for `ows:Keywords/ows:Keyword`.

![image](https://user-images.githubusercontent.com/11427611/152537477-4b4c3b36-cde6-4720-bf28-97afc538176a.png)

(from @heidivanparys)
> Regarding the text in `ows:Type`, its meaning is the same as `MD_Identification.keywords.type` from ISO 19115/ISO 19119 – see the table below from the [OGC Web Services Common Specification](https://portal.ogc.org/files/?artifact_id=20040) – which is "Method used to group similar keywords" ([ISO 19115:2003](http://iso.sparxcloud.com?m=1&o=9E5E77BE-42D0-41bf-928E-5C6A544AF5A8)) or "subject matter used to group similar keywords" ([ISO 19115-1:2014](http://iso.sparxcloud.com?m=1&o=103E85FC-80A6-4e7d-84B4-8E5E6329E312)), and its domain value is a code list with some example values on [this diagram](http://iso.sparxcloud.com?m=1&o=103E85FC-80A6-4e7d-84B4-8E5E6329E312) from the [ISO/TC 211 harmonized model](https://github.com/ISO-TC211/HMMG/wiki#webea-access).
> 
> So that text could in our case be e.g. "EU legal document", "EU legal document", "degree of conformity", see examples above. It should not be "URI". I noticed that the examples in http://schemas.opengis.net/wfs/2.0/examples/GetCapabilities/ use `<ows:Type>String</ows:Type>`, but that seems to be a mistake...
> 
> ![image](https://user-images.githubusercontent.com/11427611/151056229-72489208-51f4-4a73-8fea-3665915ef13a.png)
> 
> ![image](https://user-images.githubusercontent.com/11427611/151058032-2c46bc5a-56ad-4570-9dfc-cd6d9004e7ce.png)

(from @AntoRot)
> FS specification, but @heidivanparys said
> 
> > that seems to be a mistake...
> 
> I have no elements to say that value is a mistake. If so, I think that also "EU legal document", "EU legal document", "degree of conformity" could be a mistake (e.g. because those values don't come from the code list `MD_KeywordTypeCode` seen the mapping in the mentioned table D.5).
> 
> In any case as the `ows:Type` element is optional and doesn't provide any added value in my opinion, it can be omitted.

I did some more research, and found OGC Best Practice [OGC 08-167r2, Semantic annotations in OGC standards](https://portal.ogc.org/files/?artifact_id=47857). I added the relevant sections here. They seem to confirm what I wrote earlier. However, I've written a mail to the WFS standard editor to ask about this.

![image](https://user-images.githubusercontent.com/11427611/152536642-f1dd3495-2287-4609-9062-5708afce3ed9.png)

![image](https://user-images.githubusercontent.com/11427611/152536700-2bd77463-cb86-4f2a-842c-9f8415e60ab6.png)

![image](https://user-images.githubusercontent.com/11427611/152536751-1781fb14-2df4-418f-88b0-434edeadc6c5.png)

Note the following from those pages:

> [...] Here the Keywords element is shown as part of the ServiceIdentification element [...] It must be noted that there can be only one ‘Type’ element per ‘Keywords’ section, hence having all keywords within a ‘Keywords’ section belonging to the same thesaurus (if any). If keywords from different thesauri are needed, multiple ‘Keywords’ sections can be used. [...] there is no way to express a conceptURI that is not an extension of its thesaurusURI. Therefore, a change request should be issued to add the ability to have full-fledged annotations in OGC capabilities, i.e. having each a mandatory concept URI, and optional label, language and thesaurus URI/label. Much like what gmx:Anchor offers.

Of course, the group can choose to require URIs as keyword instead of labels, as also discussed in #39.

It is not required, but [quite some data providers add the INSPIRE theme in the service metadata as well](https://inspire-geoportal.ec.europa.eu/proxybrowser/#fq=resourceType%3Aservice&fq=keywordThesaurusURI%3A%22http%3A%2F%2Fwww.eionet.europa.eu%2Fgemet%2Finspire_themes%22&q=*%3A*), so an example for doing that in the Capabilities would be good, I think:

```xml
      <ows:Keywords>
         <ows:Keyword>Administrative Units</ows:Keyword>
         <ows:Type codeSpace="http://www.eionet.europa.eu/gemet/inspire_themes">INSPIRE theme</ows:Type>
      </ows:Keywords>
```

or

```xml
      <ows:Keywords>
         <ows:Keyword>http://inspire.ec.europa.eu/theme/au</ows:Keyword>
         <ows:Type codeSpace="http://www.eionet.europa.eu/gemet/inspire_themes">INSPIRE theme</ows:Type>
      </ows:Keywords>
```

**Comment by MarieLambois** [comment]
Reading the OWS specification, some wordings are effectively unclear. However the UML seems to allow any CharacetrString:
![image](https://user-images.githubusercontent.com/12797943/174759464-72f04527-f25d-4b17-8378-e0bbe511a7fc.png)
From a more practical point of view it seems that tools can accomodate any value for the type:
![image](https://user-images.githubusercontent.com/12797943/174760940-7c72bd94-c65f-46b4-9d1c-afff7b549adf.png)

**Comment by jescriu** [comment]
I think current use of keywords in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md is already consistent with the OWS specification.
Is there something missing, @heidivanparys and @MarieLambois?

**Comment by heidivanparys** [comment]
This issue can be closed indeed as far as I can see. On review, I noticed an inconsistency regarding the use of `ows:Type` we agreed on in the related issue #39, so I created #70 for that.
