### ISSUE TITLE
Spatial data service category

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#47]
How about the required keyword indicating the [spatial data service category](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory), has that been discussed earlier?

https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId24:

> 3.   KEYWORD
> 
> If the resource is a spatial data service, at least one keyword from Part D.4 shall be provided.

https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId81

> 4.   CLASSIFICATION OF SPATIAL DATA SERVICES
> 
> The keywords are based on the geographic services taxonomy of EN ISO 19119. This taxonomy is organised in categories, the subcategories defining the value domain of the classification of spatial data services.

This may be related to #46. E.g., for a WFS service:

```xml
      <ows:Keywords>
         <ows:Keyword>Feature access service</ows:Keyword>
         <ows:Type codeSpace="https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory">spatial data service category</ows:Type>
      </ows:Keywords>
```

or

```xml
      <ows:Keywords>
         <ows:Keyword>infoFeatureAccessService</ows:Keyword>
         <ows:Type codeSpace="https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory">spatial data service category</ows:Type>
      </ows:Keywords>
```

or

```xml
      <ows:Keywords>
         <ows:Keyword>http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoFeatureAccessService</ows:Keyword>
         <ows:Type codeSpace="https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory">spatial data service category</ows:Type>
      </ows:Keywords>
```

**Comment by AntoRot** [comment]
I agree with the proposal.

**Comment by heidivanparys** [comment]
Meeting 2022-06-21:

Antonio: the current version of the validator approves all options for ISO 19139 metadata.

To be checked by @jescriu: what does the Geoportal/validator do with keywords in the (WFS) GetCapabilities?

**Comment by jescriu** [comment]
@heidivanparys,
I think the only check pending is in the INSPIRE Reference Validator. Since the current INSPIRE Geoportal will be dismissed, it makes no sense to check it. Perhaps the new GeoNetwork backend.

**Comment by heidivanparys** [comment]
I created #71 for a suggestion of how this could be resolved. Please review.
