### ISSUE TITLE
Missing requirements on the presence of a view service and download service

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#48]
From clause 8.1:

![image](https://user-images.githubusercontent.com/11427611/157898535-d639a214-77c9-4459-8750-282c6cb708de.png)

When looking again the Good Practice, I noticed that this is actually not present in the form of requirements. The current requirements do not contain a sentence like “A Resource Locator to an INSPIRE View Service providing view access to the described data set or data set series SHALL be given.”.

In addition, I assume that it is still possible to provide other kinds of “online resources” using the  `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource` element, apart from a view and download service, and that the requirements for providing `gmd:protocol`, `gmd:applicationProfile` do not apply there. So the requirements should allow for that and not suggest otherwise.

And a final remark: requirement `/req/view-linkage` and `/req/download-linkage` have dependencies. In OGC specifications, requirements don’t have dependencies on other requirements. _Requirements classes_ can have dependencies on other _requirements classes_.

Therefore, would it be an option to do something like the following instead?

- Rephrase `/req/view-linkage` and `/req/download-linkage`, give them more subrequirements.
- Remove `/req/resource-locator-url`, `/req/resource-locator-protocol` and `/req/resource-locator-application-profile`.
- Keep `/rec/resource-locator-url` and `/rec/resource-locator-application-profile` (these will also apply to those other kinds of “online resources”, but that is in line with the general recommendation to use `gmx:Anchor`.

| Requirement | /req/view-linkage | Note |
|---|---|---|
| A | A Resource Locator to an INSPIRE View Service providing view access to the described data set or data set series SHALL be given. It SHALL be encoded using the `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource` element. |  |
| B | The element `gmd:URL` SHALL point to the response of the Get View Service Metadata request of the View Service | Instead of /req/resource-locator-url. |
| C | The element `gmd:protocol` SHALL be present. | Instead of /req/resource-locator-protocol, A |
| D | If the element `gmd:protocol` is encoded using `gmx:Anchor`, the attribute `gmx:Anchor/@xlink:href` SHALL point to the URI of one of the values in https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue. | Instead of /req/resource-locator-protocol, B and C. |
| E | If the element `gmd:protocol` is encoded using `gco:CharacterString`, the text value of `gco:CharacterString` SHALL match the label of one of the values in https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue in the language of the metadata language. | Instead of /req/resource-locator-protocol, C |
| F | The element `gmd:applicationProfile` SHALL be present. | Instead of /req/resource-locator-application-profile, A |
| G | If the element `gmd:applicationProfile` is encoded using `gmx:Anchor`, the attribute `gmx:Anchor/@xlink:href` SHALL point to https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view. | Instead of /req/resource-locator-application-profile, B and C. The exact value can be specified by having this as a subrequirement. |
| H | If the element `gmd:applicationProfile` is encoded using `gco:CharacterString`, the text value of `gco:CharacterString` SHALL match the label of https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view in the language of the metadata language. | Instead of /req/resource-locator-application-profile, C. |

| Requirement | /req/download-linkage | Note |
|---|---|---|
| A | A Resource Locator to an INSPIRE Download Service providing download access to the described data set or data set series SHALL be given. It SHALL be encoded using the `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource` element. |  |
| B | The element `gmd:URL` SHALL point to the response of the Get Download Service Metadata request of the Download Service | Instead of /req/resource-locator-url. |
| C | The element `gmd:protocol` SHALL be present. | Instead of /req/resource-locator-protocol, A |
| D | If the element `gmd:protocol` is encoded using `gmx:Anchor`, the attribute `gmx:Anchor/@xlink:href` SHALL point to the URI of one of the values in https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue. | Instead of /req/resource-locator-protocol, B and C. |
| E | If the element `gmd:protocol` is encoded using `gco:CharacterString`, the text value of `gco:CharacterString` SHALL match the label of one of the values in https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue in the language of the metadata language. | Instead of /req/resource-locator-protocol, C |
| F | The element `gmd:applicationProfile` SHALL be present. | Instead of /req/resource-locator-application-profile, A |
| G | If the element `gmd:applicationProfile` is encoded using `gmx:Anchor`, the attribute `gmx:Anchor/@xlink:href` SHALL point to https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/download. | Instead of /req/resource-locator-application-profile, B and C. The exact value can be specified by having this as a subrequirement. |
| H | If the element `gmd:applicationProfile` is encoded using `gco:CharacterString`, the text value of `gco:CharacterString` SHALL match the label of https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/download in the language of the metadata language. | Instead of /req/resource-locator-application-profile, C. |

**Comment by heidivanparys** [comment]
An additional comment:

Requirements `/req/view-linkage` and `/req/download-linkage` and recommendations `/rec/resource-locator-url` and `/rec/resource-locator-application-profile` would of course still be part of requirements class “INSPIRE-Data-Set-Metadata-Resource-Locator”. As already indicated in #45, I would be more precise regarding the target type, and add the relevant dependency:

| Requirements class | http://inspire.ec.europa.eu/id/spec/ds-linking-simplification/1.0/ds-md-resource-locator |
| --- | --- |
| Target type | ~Data set metadata~ ISO/TS 19139:2007 Geographic information Metadata XML schema implementation |
| Dependency | ~N/A~ https://inspire.ec.europa.eu/id/ats/metadata/2.0/datasets-and-series |

Note: https://inspire.ec.europa.eu/id/ats/metadata/2.0/datasets-and-series is actually the URI of the conformance class, not of the requirements class, but I'm not that distinction was really made for the TG MD?

**Comment by heidivanparys** [comment]
Meeting 2022-06-21:

Take into account the new proposal regarding TG Requirement 1.8: metadata/2.0/req/datasets-and-series/resource-locator.

One difference is the requiring vs recommending `gmx:Anchor`.

Jordi: as in Part A, the group already agreed on still allowing `gco:CharacterString`, a revised proposal should be made for TG Requirement 1.8: metadata/2.0/req/datasets-and-series/resource-locator, to allow for `gco:CharacterString`.

**Comment by heidivanparys** [comment]
The outcome of the meeting on the 21st of June was to have a look again the original proposal regarding TG Requirement 1.8 metadata/2.0/req/datasets-and-series/resource-locator, in the [discussion paper v0.5](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/resources/Discussion%20Paper%20on%20data-service%20linking%20v0.5.docx).

My thoughts after looking at this again:

The discussion paper only describes the simplified approach, and what would have to be changed to allow that approach. It seems that there is consensus that the current approach – with service metadata – and the simplified approach should co-exist. Hence, the TG metadata cannot be updated to only support the simplified approach. Therefore, the **requirements regarding `gmd:applicationProfile` and `gmd:protocol`** should not be added to TG Requirement 1.8, they should stay in this new good practice.

Regarding the **multiplicity**: 0..* or 2..*: one argument in favour of

- keeping it 0..* in the TG metadata
- and keeping the requirements for having a download service and a view service as specified in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/48#issue-1166587076 in the good practice

could be that in [Chapter 3.1, INSPIRE data sets and data set series baseline metadata, of the TG metadata](https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.2/metadata/metadata-iso19139/metadata-iso19139.adoc#31-baseline-metadata-for-data-sets-and-data-set-series), you only check for compliance with the IR metadata. The IR metadata say that the resource locator is “Mandatory if a URL is available to obtain more information on the resource, and/or access related services.”. This means if that for a dataset, if the metadata record is already available, but the service is not yet available, you can already comply with the IR metadata and “go in green” with the reference validator.

Of course, in order to conform with the Directive as a whole, you would have to create those services, and then update the dataset metadata record. And the checks for having the resource locators present are then in a different conformance class, and thus the requirements are somewhere else, not in TG 1.8, but in this case in the good practice, in a new requirements class.

Regarding **`gco:CharacterString` and `gmx:Anchor`**: I agree with Jordi that it would be best to stick to the way it was agreed on in the group, instead of going back to the proposal in the discussion paper (where only `gmx:Anchor` is allowed).

**Comment by heidivanparys** [comment]
> Regarding **`gco:CharacterString` and `gmx:Anchor`**: I agree with Jordi that it would be best to stick to the way it was agreed on in the group, instead of going back to the proposal in the discussion paper (where only `gmx:Anchor` is allowed).

This is related to #11.

**Comment by MarieLambois** [comment]
I agree with the principle of a new requirement class. 
I also think that it would be better to have it described in the Good practice. In addition to @heidivanparys arguments, I would say that it would seem strange to have an additional set of requirements for a simplification purpose. You need the full GP to understand the advantages of this approach. 
Furthermore, the validation that this aspect will not be done by the validator but by the linkage checker I think.

**Comment by idevisser** [comment]
for my understanding, we leave the current requirements classes as they are because current method is still valid. In addition, We are adding new requirement classes for the simplified approach.
This concerns the requirement classes for 
1. GP dataset metadata - additional requirements for resource locator elements as discussed above, 
2. GP network services - additional requirements for metadata in the service itself (from the mapping GP annex B) and 
 removing some of the existing requirements  because  extended capabilities are removed

The GP dataset metadata requirement class is additional to the existing dataset metadata requirement classes.
The GP network service requirement classes replaces the current network service requirement classes when the simplified approach is applied

this means we have three options for documenting the requirements 
1. add an extra scenario to the TG's metadata and network services for the simplified approach with additional requirements and changing requirements
2. make certain requirements in the current TGs conditional for the simplified approach or for the current method
3. or we leave the current TGs as they are and also include in the GP document which requirements of the network services change and expire

**Comment by jescriu** [comment]
**Meeting on 2022-09-23**
Decided to go to Option 1 (Adding Scenario 3)

**Comment by jescriu** [comment]
Dear @heidivanparys, @MarieLambois, @idevisser and @AntoRot,
I updated https://github.com/jescriu/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md taking into account the outcomes of this issue,including also the last version of the INSPIRE models graphics on the simplification approach (#44).
Please, take a look.
In the meantime, I will check (tomorrow) which if other changes are required according #45, #46 and #47.

**Comment by jescriu** [comment]
Since there has been no additional comments by the team, I proceed to close this issue.
I will proceed with a pull request when checking the missing issue stated above
Thank you all.

**Comment by jescriu** [comment]
I created a pull request and merged it into https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md
Please, @heidivanparys, @AntoRot, @idevisser, @MarieLambois, revise it.
