### ISSUE TITLE
Part B - Question tables in Annex B

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#50]
Regarding Annex B: should it contain tables like tables 17 and 19 in the TG Download? These are basically tables that show how the metadata elements present in Table 2, Metadata for spatial data services, in the [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224) are implemented (but see also #52).

A start for WFS (not complete!):

| INSPIRE Metadata elements         | WFS 2.0 without ExtendedCapabilities + ISO/TS 19139:2007 metadata record dataset                                                                                   |
|-----------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Resource Title (M)                | ows:ServiceIdentification/ows:Title                                                                                                                                |
| Resource Abstract (M)             | ows:ServiceIdentification/ows:Abstract                                                                                                                             |
| Resource Type (M)                 | discard: by default "service"                                                                                                                                      |
| Resource Locator (C)              | Resource Locator in the data set metadata (add path?)                                                                                                                                                                   |
| Coupled Resource (C)              | wfs:MetadataURL (per feature type)                                                                                                                                 |
| Spatial Data Service Type (M)     | gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:applicationProfile |
| Keyword (M)                       | ows:Keywords/ows:Keyword                                                                                                                                           |
| Geographic Bounding Box (M)       | (bounding box of data set metadata record)                                                                                                                         |
| Temporal Reference (M)            | https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/40                                                                                    |
| Spatial Resolution (C)            |                                                                                                                                                                    |
| Conformity (M)                    | https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/39                                                                                    |
| Conditions for Access and Use (M) |                                                                                                                                                                    |
| Limitations on Public Access (M)  |                                                                                                                                                                    |
| Responsible Organisation (M)      |                                                                                                                                                                    |
| Metadata Point of Contact (M)     | `WFS_Capabilities/ows:ServiceProvider/ows:ProviderName` and `WFS_Capabilities/ows:ServiceProvider/ows:ServiceContact/ows:ContactInfo/ows:Address/ows:ElectronicMailAddress` (https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/41)                                                                           |
| Metadata Date (M)                 | https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/42                                                                                    |
| Metadata Language (M)             |                                                                                                                                                                    |

Similar tables would have to be added for WMS and Atom (and WMTS as well, I assume)?

**Comment by heidivanparys** [comment]
Meeting 2022-06-21:

Ok, suggestion to have one table, with a column for each service type.

**Comment by jescriu** [comment]
Does this means that we shall restructure the tables currently provided in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md ?

**Comment by heidivanparys** [comment]
My original proposal was based on the idea that the document developed in this project would be the final document. As we agreed to integrate the changes in the current TGs, see https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/48#issuecomment-1255185172, perhaps we shouldn't use our time on rewriting and reformatting the tables in Annex B, and use it on the change proposals to the TGs instead. So that would mean that we would add the table from https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/50#issue-1166662939 to the TG download, in the section that describes scenario 3.
