### ISSUE TITLE
Part A

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/gp-data-service-linking-simplification#54]
Hi,
Where can I find part A of this work?

**Comment by hallinpihlatie** [comment]
Please confirm if it this discussion paper?
https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/resources/Discussion%20Paper%20on%20data-service%20linking%20v0.5.docx

**Comment by fabiovinci** [comment]
Dear @hallinpihlatie,

the final result of Part A is available here: https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md

**Comment by jescriu** [comment]
I closed this issue which is already solved.
Best,
Jordi
