### ISSUE TITLE
TG Metadata - Data-service linking simplification for ISO/TS 19139:2007 metadata

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#60]
# Change proposal description
This change proposal is the outcome of the work done in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/ that relates to the TG Metadata.

## Addressed TG
[Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007](https://github.com/INSPIRE-MIF/technical-guidelines/tree/main/metadata/metadata-iso19139)

## Location
Section [3. Conformance Classes for data sets](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#conformance-classes-for-data-sets)

Section [1.4 Position and structure of this document](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#position-and-structure-of-this-document)

## Issue faced
Section [3. Conformance Classes for data sets](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#conformance-classes-for-data-sets) should be updated to contain an additional requirements class, “INSPIRE data set metadata resource locator”.

![image](https://user-images.githubusercontent.com/11427611/194306060-38f2f1b9-bf77-47fe-a705-2e62dda456b5.png)

![image](https://user-images.githubusercontent.com/11427611/194305760-3ae8389c-e719-4c55-83b3-daa70017c047.png)

(original image from https://github.com/inspire-eu-validation/metadata/blob/2.0/README.md)

In addition, in section “Position and structure of this document”, it should be clarified that service metadata can be made in accordance with other TGs.

## Proposed solution

Add the description of the requirements class, as created by the Subgroup 2.3.2 (Data and Service Linking simplification).

### Pull request

New requirement class: TODO.

Section “Position and structure of this document”: https://github.com/INSPIRE-MIF/technical-guidelines/pull/75.

# Additional information

## Relevant legislation

[IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02008R1205-20081224)

## Impact on IR

No impact.

## Impact on INSPIRE validator

TODO

## Impact on INSPIRE XML schemas
No impact.

## Impact on INSPIRE code lists
No impact.

## Change proposer
Subgroup 2.3.2 (Data and Service Linking simplification)

## References

https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/

**Comment by AntoRot** [comment]
Generally the name of the CC is not the name of a specific metadata element. I'd rename the new proposed CC differently as something like "INSPIRE data-service linking metadata".

**Comment by heidivanparys** [comment]
Created https://github.com/INSPIRE-MIF/technical-guidelines/issues/108, so closing this one.
