### ISSUE TITLE
Question changes TG Download regarding Atom

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#62]
What would the concrete changes for the TG Download regarding Atom be?

For WFS and WMS, a third scenario will be added. For Atom, would the changes be

1. an update of 5.1.3 Download Service Feed: feed „link‟ element – service metadata
2. an update of the table below

?

![image](https://user-images.githubusercontent.com/11427611/194346937-c277a3d2-073f-460c-83fa-827885d54a73.png)

![image](https://user-images.githubusercontent.com/11427611/194346256-da6a4e61-1094-4d9e-8b6e-d3334dd56215.png)

**Comment by AntoRot** [comment]
As external ISO 19139 service metadata (referred in the section 5.1.3) is no longer provided for services in the simplification approach, I think that the changes affecting Atom services should be an update of the section 5.1 (before the sub-sections 5.1.1, 5.1.2, ...) and of the Table 17 by adding the new mapping elements agreed in the subgroup and describing the simplification approach.
Consequently, the feed "link" element for service metadata (referred to in section 5.1.3) should be used only from the providers that don't use the simplification approach (for the reason explained above).

**Comment by heidivanparys** [comment]
Ok, then I actually think that we need two scenarios for Atom:

- the first one is the current approach, so we don't break anything for existing implementations, thus keep Table 17, and have TG requirement 6 in this scenario (only)
- and the second one is the new and simplified approach, with a new table having the contents as described at https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md#atom-2

**Comment by MarieLambois** [comment]
Yes I agree, the scenario will be really close but still it seems clearer to have 2 scenarios just like in the other services.

**Comment by AntoRot** [comment]
I agree too. But, besides the new table, we need also revise some requirements such as the TG Requirement 6 in the section 5.1.3, as suggested for the conformity element (see https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md#35-conformity-)

**Comment by heidivanparys** [comment]
I updated https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/63, please review.

**Comment by heidivanparys** [comment]
Closing this issue, see https://github.com/INSPIRE-MIF/technical-guidelines/issues/105.
