### ISSUE TITLE
Part B - Remapping of Extended Capabilities - About Keywords

### ISSUE THREAD

**Issue by MarieLambois** [INSPIRE-MIF/gp-data-service-linking-simplification#67]
_(I could not find the Keyword issue so I open one here)_
Currently the mapping for ATOM with Keywords says not mapped. However I think that `atom:category` could fit. Any objection ?

**Comment by heidivanparys** [comment]
+1

I think that is exactly what `atom:category` is intended for. From https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.2

![billede](https://user-images.githubusercontent.com/11427611/200027463-0d6b0fcc-20c2-48b9-a412-20dff2200ccd.png)

**Comment by AntoRot** [comment]
I agree too.

**Comment by jescriu** [comment]
Dear @MarieLambois, @heidivanparys, @AntoRot,
I think this issue could be closed - Could you check, @MarieLambois?

**Comment by MarieLambois** [comment]
Since there is no ojection, I close the issue.
