### ISSUE TITLE
Good Pracitce: Data Service Linking Simplification - diagrams missing / with broken links

### ISSUE THREAD

**Issue by GDIAnja** [INSPIRE-MIF/gp-data-service-linking-simplification#74]
Could somebody please fix the broken links within the "Good Pracitce: Data Service Linking Simplification"?

URL: https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/good-practice/data-service-linking-simplification-spec.md

Missing diagrams: 
- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/good-practice/graphics/INSPIRE_models_v1.5_1.jpg
- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/good-practice/graphics/INSPIRE_models_v1.5_2.jpg
- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/good-practice/graphics/Clause_8-1_ReqClassDependencies_v1.jpg

Maybe sometimes it is better to publish a fixed and perfectly layouted pdf instead of those hard to read "github-only"-publications. The diagrams will stay in a pdf, not matter what you do with it. Nobody can be sure about what github does with diagrams over time. There is no persistency.

**Comment by jescriu** [comment]
Dear @GDIAnja,
Somehow the graphics were not added to the repository.
Now this is corrected and the specification should be complete.
Let us know if you spot any other broken link.

**Comment by GDIAnja** [comment]
Thanks a lot Jordi!
