### ISSUE TITLE
Is this simplification included in the validator?

### ISSUE THREAD

**Issue by IoannaTsakalakidou** [INSPIRE-MIF/gp-data-service-linking-simplification#75]
Hi, 

Does the validator consider the suggested simplification in the dataset metadata, view service and download service?

**Comment by fabiovinci** [comment]
Dear @IoannaTsakalakidou,

not at the moment, but new ATSs/ETSs will be developed in the coming months, and related tests will soon be made available in Reference Validator.

**Comment by IoannaTsakalakidou** [comment]
Hi @fabiovinci, 

Thank you for letting me know. How can I keep track of the changes applied to the Reference Validator?

**Comment by fabiovinci** [comment]
In general, you can follow the [helpdesk-validator](https://github.com/INSPIRE-MIF/helpdesk-validator) repository, for all the related activities.

In particular, all the changes, including new features, are documented on the [release page](https://github.com/INSPIRE-MIF/helpdesk-validator/releases).

**Comment by jescriu** [comment]
Dear @fabiovinci,
Could you please provide an update on the development of ATSs/ETSs related to this good practice?

**Comment by fabiovinci** [comment]
Dear all,

you can find all the updates related to the integration of this good practice in this [Discussion](https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/1009).

**Comment by jescriu** [comment]
Thank you @fabiovinci.

Dear @IoannaTsakalakidou, please follow up using ths Discussion @fabiovinci kindly referenced above.
I proceed to close this issue.
