### ISSUE TITLE
Italian approach

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#8]
I agree with the [proposal shared by France](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/FRA/FRA-proposal.md) which is in line with what agreed under the action 2019.2. I add the clarification that the [protocol values register](https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue) is already published in the INSPIRE registry.

In Italy the metadata elements and the codes agreed under the mentioned action are all included in the latest national metadata profile aligned with and extending the INSPIRE one, i.e.:

- linkage element with the URL to the access point of the service (e.g. Get Capabilities document);
- protocol element with a value coming from the register https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue;
- applicationProfile element with a value coming from the register http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType ;
- description element with the value coming from the register http://inspire.ec.europa.eu/metadata-codelist/OnLineDescriptionCode.

Consequently, all metadata records published in the national catalogue and conformant with the latest national metadata profile (and with INSPIRE metadata TGs 2.0) already include the metadata elements above.

The national profile also includes some extensions to what above, i.e.:
- the metadata elements listed above are mandatory for all datasets and, consequently, regardless the type of service;
- we extended the INSPIRE protocol values register by adding two values to cover the following cases:
  - a web page with further instructions for accessing the data set described through metadata;
  - direct access for downloading the data set described through metadata.
For the former:
```xml
...
<gmd:protocol>
   <gmx:Anchor xlink:href="http://www.w3.org/TR/xlink/">WWW:LINK</gmx:Anchor>
</gmd:protocol>
<gmd:applicationProfile>
   <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other">other</gmx:Anchor>
</gmd:applicationProfile>
...
```

For the latter:
```xml
...
<gmd:protocol>
   <gmx:Anchor xlink:href="https://registry.geodati.gov.it/metadata-codelist/ProtocolValue/www-download">WWW:DOWNLOAD</gmx:Anchor>
</gmd:protocol>
<gmd:applicationProfile>
   <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other">other</gmx:Anchor>
</gmd:applicationProfile>
...
```
In this case we added an internal item as no reference code is published in a controlled vocabulary/register yet.

Recently the national community proposed to add also the name element (as a recommended element).

I proposed a change to add the two items above in the INSPIRE Protocol Value register (see the [issue submitted](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/17)), but the control body preferred not to approve the change as the addition of new values would have implied a change in the definition and reasoning behind the code list.

I ask the group to discuss the possible addition of those items in the INSPIRE register in order to reopen the issue if agreed, as the control body suggested. 

I also share an example of a metadata record published in the national catalogue including the information about both an Atom service and a link to directly download the dataset: https://geodati.gov.it/RNDT/rest/document?id=p_tn:EPC4EU_APRIE_all.

**Comment by dartasensi** [comment]
Dear @AntoRot 

thanks for sharing your experience and knowledge on the current Italian implementation regarding the ResourceLocator elements.

Regarding the codelist addition, I think it's a good approach: if it is still relevant, we can discuss it in this subgroup, to reach a critical mass and reopen the issue with the control body.

**Comment by AntoRot** [comment]
Dear @dartasensi 

the issue is still relevant. I shared it just for discussing it in this subgroup and, if agreed, reopen it in the helpdesk-registry repository (as suggested by the control body itself).

Thank you,
Antonio

**Comment by AntoRot** [comment]
x

**Comment by AntoRot** [comment]
This was my initial contribution to the discussion about the simplification action. 
It required no decision and consequently I close it.

**Comment by AntoRot** [comment]
This was my initial contribution to the discussion about the simplification action.
It required no decision and consequently I close it.

**Comment by AntoRot** [comment]
Closed issue
